### ISSUE TITLE
я наверн туплю. но следую в точности по инструкции, пишет ошибку Requested Python version (2) is not installed

### ISSUE THREAD

**Issue by LdieSU7** [Rast1234/vkd#10]
можно более конкретную инструкцию, для еще более тупых)
на шестом пункте инструкции, сталкиваюсь с ошибкой `Requested Python version (2) is not installed`
или
![2021-02-22 16_25_11-Windows PowerShell](https://user-images.githubusercontent.com/62698341/108714454-9b544700-752a-11eb-8565-c651611145c1.png)
я наверн туплю. но следую в точности по инструкции, пишет ошибку Requested Python version (2) is not installed

**Comment by Rast1234** [comment]
1. юзай `python main.py ....`
2. `python --version` что показывает? если 3.что-нибудь, надо установить **python 2** https://www.python.org/download/releases/2.0/
3. тогда возможно надо будет его запускать так: `python2 main.py ...`

**Comment by Rast1234** [comment]
ключ не пали, это же по сути полный доступ к учетке!

**Comment by LdieSU7** [comment]
> ключ не пали, это же по сути полный доступ к учетке!

насчет ключа или доступа к аккаунту это все бред. ну и к тому же здесь, на гитхабе, абсолютно все логируется. т.е любой может нажать историю редактирования сообщения и посмотреть))
ps аккаунт стоит 25-30 рублей с гарантией замены. это так

ну а касательно python --version и python main.py
![2021-02-22 17_35_10-Windows PowerShell](https://user-images.githubusercontent.com/62698341/108722535-559c7c00-7534-11eb-9546-4fe256dacfec.png)

а это при попытке запуска "BeOpen-Python-2.0.exe"
![2021-02-22 17_32_59-Невозможно запустить это приложение на вашем ПК](https://user-images.githubusercontent.com/62698341/108722540-56351280-7534-11eb-99c2-43a60ec1dfbc.png)

**Comment by Rast1234** [comment]
ну про историю то понятно, тем не менее лучше глаза не мозолить. если ключ или акк не жалко то ок =)

у тебя в системе установлен python 3, а нужен python 2. если установлены оба, у них может быть конфликт, когда пишешь `python` то выполнится первый попавшийся. попробуй указать полный путь к интерпретатору, типа `c:\python28\python.exe`

а что такое `BeOpen-Python-2.0.exe` я без понятия

**Comment by LdieSU7** [comment]
> а что такое BeOpen-Python-2.0.exe я без понятия

ну, ты скинул ссылку https://www.python.org/download/releases/2.0/
![image](https://user-images.githubusercontent.com/62698341/108723646-8fba4d80-7535-11eb-93d7-7647774753db.png)

здесь вроде норм установщик) https://www.python.org/download/releases/2.7/

**Comment by LdieSU7** [comment]
все равно не работает
`Traceback (most recent call last):
  File "main.py", line 255, in <module>
    main()
  File "main.py", line 184, in main
    (response, json_stuff) = call_api("wall.get", [("owner_id", args.id), ("count", 1), ("offset", 0)], args)
  File "E:\My\Download\Browser\GoogleChrome\Profileremote\vkd-master\vkd-master\Api.py", line 61, in call_api
    raise RuntimeError(msg)
RuntimeError: API call resulted in error (8): Invalid request: v is required. Version param should be passed as "v". "version" param is invalid and not supported.`
![image](https://user-images.githubusercontent.com/62698341/108724731-b6c54f00-7536-11eb-943d-ca814f82f46e.png)

> ну про историю то понятно, тем не менее лучше глаза не мозолить. если ключ или акк не жалко то ок =)

![image](https://user-images.githubusercontent.com/62698341/108724695-add47d80-7536-11eb-8e09-6d2bb3dfd3bd.png)

**Comment by Rast1234** [comment]
Да, мой косяк, ссылку с главной страницы взял, она кривая оказалась. Ну теперь скрипт запустился, только vk api отдает ошибку. Значит, скрипт окончательно устарел и работать без переделки не будет :(

**Comment by LdieSU7** [comment]
> Да, мой косяк, ссылку с главной страницы взял, она кривая оказалась. Ну теперь скрипт запустился, только vk api отдает ошибку. Значит, скрипт окончательно устарел и работать без переделки не будет :(

но при этом VOffline до сих пор кое-как работает.. правда жалко что там у комментариев к посту не пишутся ссылки на прикрепленные элементы, только количество((

**Comment by Rast1234** [comment]
Voffline более новый просто. Давай там в issue пример с постом и что ты хочешь из него получить чуть подробнее, я посмотрю можно ли прикрутить
