### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by anton-malakhov** [Rast1234/vkd#2]
## Output:

Please open this url:
...
Wall dowload start
Downloading: ......jpg (63 kb)
Downloading...
...
 Traceback (most recent call last):]]
  File "./main.py", line 255, in <module>
    main()
  File "./main.py", line 194, in main
    (post, json_stuff) = call_api("wall.get", [("owner_id", args.id), ("count", 1), ("offset", x)], args)
  File "/mnt/tbbusers/amalakho/archive/vkd-master/Api.py", line 46, in call_api
    json_stuff = urllib2.urlopen(url).read()
  File "/usr/lib64/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
urllib2.URLError: urlopen error [Errno -2] Name or service not known

**Comment by arpit1997** [comment]
Good Project @Rast1234 
There are a few things that i want to suggest:
- you may put all your codes / scripts into a new src folder so that it will be more readable, so that it would follow a common standard. 
 - You should add a license so that use of your source code would be clarified 
- follow a ode style like PEP8 or PEP257
Ping me if there is anything wrong or if you want any help.
:small_airplane: :smile: 
 -

**Comment by Rast1234** [comment]
@arpit1997 as you might see, this project is old and rusty. I don't support it and don't see any reason to make license, follow PEP8 etc, because nobody cares, this is one-time script, not enterprise software.

**Comment by arpit1997** [comment]
It did not look like you did not care about this project. I saw readme of this project which was very good. 
I agree that it is not an enterprise software and you might not support this anymore but it might be useful for someone else. Like someone else can use your code for learning purpose or they can modify it for something  better So you can try it other than that it is your choice for your project. 
Thank you
:smiley_cat: :smiley_cat: :slightly_smiling_face:

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.
