### ISSUE TITLE
Я могу скачивать стену без музыки?

### ISSUE THREAD

**Issue by AquaGen** [Rast1234/vkd#5]
При сохранении стены очень много места занимает музыка из записей, комментариев, которую и так можно найти в интернете. К тому же приходится долго ждать, пока она загрузится.

**Comment by Rast1234** [comment]
Можно в коде поправить функцию, которая обрабатывает скачивание музыки,
чтобы она ничего не делала.

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.
