### ISSUE TITLE
Было бы круто сделать парсер по диалогам в вк

### ISSUE THREAD

**Issue by revis94** [Rast1234/vkd#8]
Парсер,вытягивающий фотки,документы и прочее был бы очень крутым дополнением!
А так работает, спасибо! Все документы вытянул со страницы :+1:

**Comment by Rast1234** [comment]
Музыка кстати должна была отвалиться, вконтакт недавно гайки закрутил...
Может доберусь до того, чтобы сделать выкачивалку всего остального и еще музыку починить, но не знаю даже когда.

**Comment by Rast1234** [comment]
А именно из диалогов по-честному ничего не достать, у сторонних приложений нет доступа к диалогам.

**Comment by revis94** [comment]
Про то, что вк теперь не дает качать музло сторонним приложенниям - почитал в сети про это - печаль :(
Про то,что у стронних приложений нет доступа к диалогам - тоже мало приятного, поскольку я хотел попробовать провернуть таким же образом авторизацию в одном из скриптов, который укажу ниже. 
А музыку можно пока и не чинить, ибо есть всякие (vkmusic, vksaver) так как судя по запросам в сети, народу очень требуется прога,которая парсит пикчи из диалогов)) Мне тоже такая была нужна))
Я пробовал заюзать пару скриптов по парсингу, все они валятся на процессе авторизации.
Вот ссылки: [https://github.com/dokxpi/VKIMexport#vkimimport-boom-013](url1) - наиболее адекватный и приведенный к законченному виду (на момент работы)
А вот этот [https://github.com/Shrikimaru/vk_dialog_photos_dump_script](url2) старый, использует remixsid_cookie , как по мне сейчас с таким методом точно не "заведется".
Сам я в python новичок, пытался ковырять первый вариант, но так и не добился успешной авторизации.
VK видимо процедуру авторизации сменил в т.ч. и процесс выдачи токена... Или я чего-то не догоняю :) Скрипт, который работал два года назад - сейчас не пашет.

**Comment by Rast1234** [comment]
Ну вообще самый надежный способ это прикинуться официальным клиентом, там и музыка и диалоги никуда не денутся. Есть же неофициальный клиент Kate Mobile, работает не хуже оригинала. Он использует app id офф клиента.
Кстати если и писать нормальную сохранялку, то точно не на питоне, потому что тяжело распространять - поди людям объясни как надо зависимости ставить, как в первом скрипте по ссылке, многие про консоль-то не знают)

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.

конкретно по этой issue, новый проект именно прикидывается официальным клиентом и полностью поддерживает аудиозаписи.
